quarkus.http.port=8080
quarkus.application.name=quarkus-mcp-server

quarkus.rest-client.api-service.url=${API_SERVICE_URL:http://mcp-api-service:8100}
quarkus.rest-client.api-service.connection-pool-size=1000
quarkus.rest-client.api-service.keep-alive-enabled=true
quarkus.redis.hosts=${REDIS_URL:redis://mcp-redis:6379}
quarkus.redis.max-pool-size=100
quarkus.redis.max-pool-waiting=1000
