spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.type=ASYNC
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Redis
spring.data.redis.url=${REDIS_URL:redis://mcp-redis:6379}
